{{/**

  Copyright (C) 2024 Dremio

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.

**/}}

{{- $httpRouteApiVersion := include "nessie.httpRoute.apiVersion" . | trim -}}
{{- if and .Values.gatewayApi.enabled (not $httpRouteApiVersion) }}
{{- fail "gatewayApi.enabled=true but no supported Gateway API version was detected for HTTPRoute" -}}
{{- end }}
{{- if and .Values.gatewayApi.enabled $httpRouteApiVersion }}
{{- $gatewayName := include "nessie.gateway.name" . -}}
{{- $gatewayNamespace := include "nessie.gateway.namespace" . -}}
{{- $defaultBackendPort := ((include "nessie.service.primaryPort" .) | trim) | int -}}
{{- $routes := .Values.gatewayApi.httpRoutes | default (list) -}}
{{- range $idx, $route := $routes }}
{{- $routeName := default (printf "%s%s" (include "nessie.fullname" $) (default "" $route.nameSuffix)) $route.name -}}
{{- $routeNamespace := default $.Release.Namespace $route.namespace -}}
{{- $rules := $route.rules | default (list) -}}
{{- if not (gt (len $rules) 0) -}}
{{- fail "gatewayApi.httpRoutes[].rules must contain at least one rule" -}}
{{- end -}}
{{- if gt $idx 0 }}
---
{{- end }}
apiVersion: {{ $httpRouteApiVersion }}
kind: HTTPRoute
metadata:
  name: {{ $routeName }}
  namespace: {{ $routeNamespace }}
  labels:
    {{- include "nessie.labels" $ | nindent 4 }}
    {{- with $route.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{ with $route.hostnames }}
  hostnames:
    {{- range . }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  {{- if $route.parentRefs }}
  parentRefs:
    {{ toYaml $route.parentRefs | nindent 4 }}
  {{- else }}
  parentRefs:
    - name: {{ $gatewayName }}
      namespace: {{ $gatewayNamespace }}
  {{- end }}
  rules:
{{- range $rule := $rules }}
    - {{- if $rule.matches }}
      matches:
        {{- toYaml $rule.matches | nindent 8 }}
      {{- end }}
      {{ with $rule.filters }}
      filters:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- $backends := $rule.backendRefs | default (list) }}
      {{- if not (gt (len $backends) 0) -}}
      {{- fail "gatewayApi.httpRoutes[].rules[].backendRefs must contain at least one backend" -}}
      {{- end }}
      backendRefs:
{{- range $backend := $backends }}
        {{- $service := $backend.service | default (dict) -}}
        {{- $computedServiceName := default (printf "%s%s" (include "nessie.fullname" $) (default "" $service.nameSuffix)) $service.name -}}
        {{- $explicitName := default "" $backend.name -}}
        {{- $name := default $computedServiceName $explicitName -}}
        {{- $serviceNamespace := default $routeNamespace $service.namespace -}}
        {{- $backendNamespace := default $serviceNamespace $backend.namespace -}}
        {{- $port := default (default $service.port $defaultBackendPort) $backend.port -}}
        {{- $kind := dig "kind" "Service" $backend }}
        - name: {{ $name }}
          {{- if $backendNamespace }}
          namespace: {{ $backendNamespace }}
          {{- end }}
          {{- with $backend.group }}
          group: {{ . }}
          {{- end }}
          kind: {{ $kind }}
          port: {{ required "gatewayApi.httpRoutes[].rules[].backendRefs[] requires a port" $port }}
          {{- with $backend.weight }}
          weight: {{ . }}
          {{- end }}
{{- end }}{{/* range $backend */}}
{{- end }}{{/* range $rule */}}
{{- end }}{{/* range $routes */}}
{{- end }}{{/* if gateway api enabled */}}