# Dependencies needed by build-logic/

[libraries]
assertj-core = { module = "org.assertj:assertj-core", version = "3.27.3" }
errorprone = { module = "net.ltgt.gradle:gradle-errorprone-plugin", version = "4.3.0" }
idea-ext = { module = "gradle.plugin.org.jetbrains.gradle.plugin.idea-ext:gradle-idea-ext", version = "1.2" }
jandex = { module = "com.github.vlsi.gradle:jandex-plugin", version = "2.0.0" }
junit-bom = { module = "org.junit:junit-bom", version = "5.13.4" }
license-report = { module = "com.github.jk1:gradle-license-report", version = "2.9" }
shadow = { module = "com.gradleup.shadow:shadow-gradle-plugin", version = "8.3.8" }
spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version = "7.2.1" }
