# Dependencies needed by build-logic/

[libraries]
assertj-core = { module = "org.assertj:assertj-core", version = "3.27.6" }
errorprone = { module = "net.ltgt.gradle:gradle-errorprone-plugin", version = "4.3.0" }
idea-ext = { module = "gradle.plugin.org.jetbrains.gradle.plugin.idea-ext:gradle-idea-ext", version = "1.3" }
jandex = { module = "org.kordamp.gradle:jandex-gradle-plugin", version = "2.3.0" }
junit-bom = { module = "org.junit:junit-bom", version = "5.14.1" }
license-report = { module = "com.github.jk1:gradle-license-report", version = "3.0.1" }
shadow = { module = "com.gradleup.shadow:shadow-gradle-plugin", version = "9.3.0" }
spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version = "8.1.0" }
