apiVersion: v2
name: nessie
description: A Helm chart for Nessie
type: application
version: 0.90.4
home: https://projectnessie.org/
icon: https://raw.githubusercontent.com/projectnessie/nessie/main/site/docs/img/nessie.svg
sources:
  - https://github.com/projectnessie/nessie
keywords:
  - nessie
  - iceberg
  - delta
  - data lake
  - transactional catalog
  - git-like semantics
maintainers:
  - name: nastra
  - name: snazy
  - name: dimas-b
  - name: adutra
