name: Synchronize Container Registries

on:
  workflow_run:
    workflows:
      - 'Publish release'
      - 'Publish in-development builds from main'
    types:
      - completed
  workflow_dispatch:

jobs:
  sync:
    name: Synchronize Container Registries
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    if: github.repository == 'projectnessie/nessie'

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Sync images
        env:
          REGCLIENT_VERSION: 0.6.1
          QUAY_IO_USER: ${{ secrets.QUAY_IO_USER }}
          QUAY_IO_TOKEN: ${{ secrets.QUAY_IO_TOKEN }}
          GHCR_IO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          curl -L https://github.com/regclient/regclient/releases/download/v${REGCLIENT_VERSION}/regsync-linux-amd64 > regsync
          sha512sum -c .github/docker-sync/regsync.sha512
          chmod 755 regsync

          ./regsync -v info -c .github/docker-sync/regsync.yml once
